#!/bin/bash

tar --listed-incremental=/run/media/lynx/arkheîon/backup/snapshot.file \
    -cJpf /run/media/lynx/arkheîon/backup/home-backup-`date +%d-%m-%Y`.tar.xz \
    /home/lynx/{Desktop,Documents,Downloads,Pictures,Music,Templates,go,texmf,playground,obs-studio,Zotero,Repositories,.bin,.texlive}
