#! /bin/bash
	MUSIC_DIR=/home/nyx/Music
	COVER=/tmp/cover.png
    BACKGROUND="/home/nyx/.popup/cover.png"
    
    {
    artist="$(mpc --format %artist% current)"
    album="$(mpc --format %album% current)"
    file="$(mpc --format %file% current)"
    album_dir="${file%/*}"
    [[ -z "$album_dir" ]] && exit 1
    album_dir="$MUSIC_DIR/$album_dir"

    covers="$(find "$album_dir" -type d -exec find {} -maxdepth 1 -type f -iregex ".*/.*\(${album}\|cover\|folder\|artwork\|front\).*[.]\(jpe?g\|png\|gif\|bmp\)" \; )"

    if [ -z "$cover" ]
    then
        sacad "$artist" "$album" 600 $album_dir/cover.jpg > /dev/null 2>&1
        covers="$(find "$album_dir" -type d -exec find {} -maxdepth 1 -type f -iregex ".*/.*\(${album}\|cover\|folder\|artwork\|front\).*[.]\(jpe?g\|png\|gif\|bmp\)" \; )"
    fi



    src="$(echo -n "$covers" | head -n1)"
    rm -f "$COVER" 
    convert "$src" -resize 150 "$COVER"
    n30f -b -x 2600 -y 50 -d ${BACKGROUND}
    n30f -b -x 2625 -y 75 -d ${COVER}
} &
