#!/bin/bash

DIR=$HOME/Pictures/snaps/
FNAME="$DIR/$(date +%s).png"

case $1 in
    "w")
        maim -i $(xdotool getactivewindow) $FNAME
    ;;

    "a")
        maim -s $FNAME
    ;;
    "f")
        maim $FNAME
    ;;
esac

if [ -f "$FNAME" ]; then
    notify-send -t 2000 "Screenshot successfully saved to $FNAME"
fi
