source $HOME/.config/nvim/plug.vim
source $HOME/.config/nvim/base.vim
source $HOME/.config/nvim/map.vim
source $HOME/.config/nvim/whitespace.vim
source $HOME/.config/nvim/history.vim
source $HOME/.config/nvim/fzf.vim
source $HOME/.config/nvim/startify.vim
source $HOME/.config/nvim/typesetting.vim
source $HOME/.config/nvim/misc.vim
